const express = require("express")
const router = express()
router.use(express.json())
const contentController = require("../controllers/content.controller.js")
const collectionController = require("../controllers/collection.controller.js")
const cmsMiddleware = require("../middlewares/cms.middleware.js")
const authMiddleware = require("../middlewares/auth.middleware.js")
router.use(authMiddleware.requestValidator)

router.get("/get-content-types", contentController.getContentTypes)
router.get("/get-collections/:contentTypeName", cmsMiddleware.contentTypeValidator, collectionController.getCollection)
router.get("/get-fields/:contentTypeName", cmsMiddleware.contentTypeValidator, contentController.getFields)
router.post("/create/contentType/:contentTypeName",cmsMiddleware.contentTypeValidator, contentController.createContentType)
router.patch("/add/field/:contentTypeName",cmsMiddleware.fieldValidator, contentController.addField)
router.post("/add/collection/:contentTypeName",cmsMiddleware.contentTypeValidator, collectionController.addCollection)
router.patch("/update/collection/:id", collectionController.updateCollection)
router.delete("/delete-collection/:id", cmsMiddleware.collectionIdValidator, collectionController.deleteCollection)
router.patch("/update/content-type-name/:contentTypeName", contentController.updateContentTypeName)
router.delete("/delete/field/:contentTypeName", contentController.deleteField)
module.exports = router 
